---
title: "Pairwise correlations"
author: "Anthony Hung"
date: "2020-05-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# plot boxplots of pairwise correlations between samples

```{r load}
library(dplyr)
library(textshape)
library(stringr)
library(reshape2)
library(ggplot2)
library(RUVSeq)
library(cowplot)
theme_set(theme_cowplot())

#load data
raw_counts <- cpm(readRDS("data/raw_counts_relabeled.rds"))

uq <- readRDS("data/norm_filtered_counts.rds")

#RUVs output for what the var partition looks like after normalization
set1 <- readRDS("data/RUVsOut.rds")
anno <- pData(set1) #unwanted factors

uq_ruv <- t(lm(t(uq) ~ anno$W_1 + anno$W_2)$residuals)
```

# Calculate cor matrices

```{r cors}
#raw
cors_raw_spear <- cor(raw_counts, method="spearman", use="pairwise.complete.obs")
cors_raw_pearson <- cor(raw_counts, method="pearson", use="pairwise.complete.obs")

#uq
cors_uq_spear <- cor(uq, method="spearman", use="pairwise.complete.obs")
cors_uq_pearson <- cor(uq, method="pearson", use="pairwise.complete.obs")

#uq_ruv
cors_uq_ruv_spear <- cor(uq_ruv, method="spearman", use="pairwise.complete.obs")
cors_uq_ruv_pearson <- cor(uq_ruv, method="pearson", use="pairwise.complete.obs")
```

# Convert cor matrices into useful format

```{r convert}
#takes as input a correlation matrix and outputs a tidy version
convert_cor <- function(cor_matrix){
     tidy <- tidy_matrix(cor_matrix)
     #remove identities
     tidy <- tidy %>% filter(value < 0.999)
     tidy$ind1 <- sapply(strsplit(tidy$row,"_"), `[`, 1)
     tidy$ind2 <- sapply(strsplit(tidy$col,"_"), `[`, 1)
     tidy$rep1 <- sapply(strsplit(tidy$row,"_"), `[`, 2)
     tidy$rep2 <- sapply(strsplit(tidy$col,"_"), `[`, 2)
     tidy$treat1 <- sapply(strsplit(tidy$row,"_"), `[`, 3)
     tidy$treat2 <- sapply(strsplit(tidy$col,"_"), `[`, 3)
     return(as.data.frame(tidy))
}

#raw
tidy_cors_raw_spear <- convert_cor(cors_raw_spear)
tidy_cors_raw_pearson <- convert_cor(cors_raw_pearson)

#uq
tidy_cors_uq_spear <- convert_cor(cors_uq_spear)
tidy_cors_uq_pearson <- convert_cor(cors_uq_pearson)

#uq_ruv
tidy_cors_uq_ruv_spear <- convert_cor(cors_uq_ruv_spear)
tidy_cors_uq_ruv_pearson <- convert_cor(cors_uq_ruv_pearson)
```

# Make plots

```{r plots}
make_plot <- function(tidy_cors){
     all <- tidy_cors$value
     same_ind <- tidy_cors$value[tidy_cors$ind1 == tidy_cors$ind2]
     same_rep <- tidy_cors$value[tidy_cors$rep1 == tidy_cors$rep2]
     same_treat <- tidy_cors$value[tidy_cors$treat1 == tidy_cors$treat2]
     
     same_ind_rest_diff <- tidy_cors$value[tidy_cors$ind1 == tidy_cors$ind2 & tidy_cors$rep1 != tidy_cors$rep2 & tidy_cors$treat1 != tidy_cors$treat2]
     same_rep_rest_diff <- tidy_cors$value[tidy_cors$rep1 == tidy_cors$rep2 & tidy_cors$ind1 != tidy_cors$ind2 & tidy_cors$treat1 != tidy_cors$treat2]
     same_treat_rest_diff <- tidy_cors$value[tidy_cors$treat1 == tidy_cors$treat2 & tidy_cors$ind1 != tidy_cors$ind2 & tidy_cors$rep1 != tidy_cors$rep2]

     same_ind_rep <- tidy_cors$value[tidy_cors$ind1 == tidy_cors$ind2 & tidy_cors$rep1 == tidy_cors$rep2]
     same_rep_treat <- tidy_cors$value[tidy_cors$rep1 == tidy_cors$rep2 & tidy_cors$treat1 == tidy_cors$treat2]
     same_ind_treat <- tidy_cors$value[tidy_cors$ind1 == tidy_cors$ind2 & tidy_cors$treat1 == tidy_cors$treat2]
     
     same_ind_rep_diff_treat <- tidy_cors$value[tidy_cors$ind1 == tidy_cors$ind2 & tidy_cors$rep1 == tidy_cors$rep2 & tidy_cors$treat1 != tidy_cors$treat2]
     same_rep_treat_diff_ind <- tidy_cors$value[tidy_cors$rep1 == tidy_cors$rep2 & tidy_cors$treat1 == tidy_cors$treat2 & tidy_cors$ind1 != tidy_cors$ind2]
     same_ind_treat_diff_rep <- tidy_cors$value[tidy_cors$ind1 == tidy_cors$ind2 & tidy_cors$treat1 == tidy_cors$treat2 & tidy_cors$rep1 != tidy_cors$rep2]
     
     diff_all <- tidy_cors$value[tidy_cors$ind1 != tidy_cors$ind2 & tidy_cors$rep1 != tidy_cors$rep2 & tidy_cors$treat1 != tidy_cors$treat2]
     
     n <- length(all)
     
     length(same_ind) <- n
     length(same_rep) <- n
     length(same_treat) <- n
     length(same_ind_rest_diff) <- n
     length(same_rep_rest_diff) <- n
     length(same_treat_rest_diff) <- n
     length(same_ind_rep) <- n
     length(same_ind_treat) <- n
     length(same_rep_treat) <- n
     length(same_ind_rep_diff_treat) <- n
     length(same_rep_treat_diff_ind) <- n
     length(same_ind_treat_diff_rep) <- n
     length(diff_all) <- n
     
     #combine all into a df
     combined <- as.data.frame(cbind(all, 
                                     #same_ind, same_treat, same_rep, 
                                     same_ind_rest_diff, same_treat_rest_diff, same_rep_rest_diff,
                                     #same_ind_treat, same_ind_rep, same_rep_treat,
                                     same_ind_treat_diff_rep, same_ind_rep_diff_treat, same_rep_treat_diff_ind,
                                     diff_all))
     #melt
     combined_melt <- melt(combined)
     
     #plot
     return(ggplot(combined_melt, aes(x = variable, y = value)) +
                 geom_boxplot() +
                 geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.2) +
                 labs(y = "correlation", x = ""))
}

#raw
make_plot(tidy_cors_raw_spear) + labs(title="Raw Data (cpm), Spearman")
make_plot(tidy_cors_raw_pearson) + labs(title="Raw Data (cpm), Pearson")
#uq
make_plot(tidy_cors_uq_spear) + labs(title="UQ normalized Data, Spearman")
make_plot(tidy_cors_uq_pearson) + labs(title="UQ normalized Data, Pearson")
#uq_ruv
make_plot(tidy_cors_uq_ruv_spear) + labs(title="uq_ruv normalized Data, Spearman")
make_plot(tidy_cors_uq_ruv_pearson) + labs(title="uq_ruv normalized Data, Pearson")
```

# Make plots comparing 18856 correlations to others

```{r NA18856}
make_plot_18856 <- function(tidy_cors){
     all <- tidy_cors$value
     NA18856_treated <- tidy_cors$value[tidy_cors$ind1 == "18856" & tidy_cors$ind2 == "18856" & tidy_cors$treat1 == "S" & tidy_cors$treat2 == "S"]
     NA18856_untreated <- tidy_cors$value[tidy_cors$ind1 == "18856" & tidy_cors$ind2 == "18856" & tidy_cors$treat1 == "U" & tidy_cors$treat2 == "U"]
     NA18855_treated <- tidy_cors$value[tidy_cors$ind1 == "18855" & tidy_cors$ind2 == "18855" & tidy_cors$treat1 == "S" & tidy_cors$treat2 == "S"]
     NA18855_untreated <- tidy_cors$value[tidy_cors$ind1 == "18855" & tidy_cors$ind2 == "18855" & tidy_cors$treat1 == "U" & tidy_cors$treat2 == "U"] 
     NA19160_treated <- tidy_cors$value[tidy_cors$ind1 == "19160" & tidy_cors$ind2 == "19160" & tidy_cors$treat1 == "S" & tidy_cors$treat2 == "S"]
     NA19160_untreated <- tidy_cors$value[tidy_cors$ind1 == "19160" & tidy_cors$ind2 == "19160" & tidy_cors$treat1 == "U" & tidy_cors$treat2 == "U"]
     
     n <- 6
     
     length(NA18856_treated) <- n
     length(NA18856_untreated) <- n
     length(NA18855_treated) <- n
     length(NA18855_untreated) <- n
     length(NA19160_treated) <- n
     length(NA19160_untreated) <- n
     
     #combine all into a df
     combined <- as.data.frame(cbind(NA18856_treated, NA18856_untreated, NA18855_treated, NA18855_untreated, NA19160_treated, NA19160_untreated))
     #melt
     combined_melt <- melt(combined) %>% distinct()
     
     #plot
     return(ggplot(combined_melt, aes(x = variable, y = value)) +
                 geom_boxplot() +
                 geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.5) +
                 labs(y = "correlation", x = ""))
}

make_plot_18856(tidy_cors_raw_spear) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
make_plot_18856(tidy_cors_uq_spear) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

