---
title: "finding_interaction_example"
author: "Anthony Hung"
date: "2020-06-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


# Load packages and normalized data

```{r load}
library(edgeR)
library(dplyr)

#raw(filtered)
counts_upperquartile <- readRDS("data/filtered_counts.rds")
#normalized
filtered_upperquartile <- readRDS("data/norm_filtered_counts.rds")
filtered_RLE <- readRDS("data/norm_filtered_counts_RLE.rds")
#metadata
sampleinfo <- readRDS("data/Sample.info.RNAseq.reordered.csv")
```

# Find top 1000 genes with least coefficient of variation amongst control samples and intersect with top 1000 genes with highest coefficient of variation amongst strain samples (between individuals)

```{r identify least variable genes ctrl}
controls <- counts_upperquartile$counts[,sampleinfo$treatment == "Unstrain"]

#input data consists of raw filtered data (filtered for lowly expressed genes)
#compute CV (stdev/mean) and rank from least to most; pick 1000 least variable
cv <- apply(controls, 1, function(x) sd(x)/mean(x))
least_var_ctl <- names(head(sort(cv), 1500))
```

```{r identify most variable genes between individuals treatment}
treateds <- counts_upperquartile$counts[,sampleinfo$treatment == "Strain"]

#input data consists of raw filtered data (filtered for lowly expressed genes)
#compute range, pick out the largest ranges
range <- apply(controls, 1, function(x) diff(range(x)))
most_var_treat <- names(head(sort(range, decreasing = TRUE), 1500))
```

```{r overlap}
candidates <- intersect(least_var_ctl, most_var_treat)

saveRDS(candidates, "output/least_var_ctl_most_var_treat.rds")

```

