---
title: "Coefficients of Variation single cell pilot"
author: "Anthony Hung"
date: "2020-03-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction
Code adapted from http://jdblischak.github.io/singleCellSeq/analysis/cv-adjusted.html

# Load Libraries and data

```{r load libraries and data}
library(Seurat)
library(DESeq2)
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(zoo)


#Pilot data
ANT1.2 <- readRDS("data/ANT1_2.rds")
ANT1.2 <- AddMetaData(ANT1.2, "iPSC-Chondrocyte", col.name = "Cell.Type")
dim(ANT1.2)
```

## Extract counts and metadata (annotations)

```{r counts}
counts <- as.matrix(ANT1.2@assays$RNA@counts)
labels <- ANT1.2@meta.data$labels
batch <- ANT1.2@meta.data$orig.ident
anno <- data.frame(cbind(labels, batch))
```


## Coefficient of variation

### compute coefficient of variation for each sample

```{r cv2}
# normalize counts
cpm_pilot <- cpm(counts, log = T)

# Compute CV and mean of normalized molecule counts (take 2^(log2-normalized count))
molecules_cv_sample <- 
  lapply(1:length(unique(anno$labels)), function(per_sample) {
      molecules_per_sample <- 2^cpm_pilot[ , unique(anno$labels) == unique(anno$labels)[per_sample] ]
      mean_per_gene <- apply(molecules_per_sample, 1, mean, na.rm = TRUE)
      sd_per_gene <- apply(molecules_per_sample, 1, sd, na.rm = TRUE)
      cv_per_gene <- data.frame(mean = mean_per_gene,
                                sd = sd_per_gene,
                                cv = sd_per_gene/mean_per_gene)
      rownames(cv_per_gene) <- rownames(cpm_pilot)
  
      # cv_per_gene <- cv_per_gene[rowSums(is.na(cv_per_gene)) == 0, ]
      cv_per_gene$sample <- unique(anno$labels)[per_sample]
      
      # Add sparsity percent
      molecules_count <- counts[ , unique(anno$labels) == unique(anno$labels)[per_sample]]
      cv_per_gene$sparse <- rowMeans(as.matrix(molecules_count) == 0)
        
      return(cv_per_gene)
      }) 
names(molecules_cv_sample) <- unique(anno$labels)

sapply(molecules_cv_sample, dim)
```

### Compute distance to the median to correct our CV2s

```{r rolling median}
#convert list into a df
df_plot <- do.call(rbind, molecules_cv_sample)

# Compute a data-wide coefficient of variation on CPM normalized counts.
data_cv <- apply(2^cpm_pilot, 1, sd)/apply(2^cpm_pilot, 1, mean)

# Order of genes by mean expression levels
order_gene <- order(apply(2^cpm_pilot, 1, mean))

# Rolling medians of log10 squared CV by mean expression levels
roll_medians <- rollapply(log10(data_cv^2)[order_gene], width = 50, by = 25,
                         FUN = median, fill = list("extend", "extend", "NA") )
ii_na <- which( is.na(roll_medians) )
roll_medians[ii_na] <- median( log10(data_cv^2)[order_gene][ii_na] )

names(roll_medians) <- rownames(cpm_pilot)[order_gene]

# re-order rolling medians
reorder_gene <- match(rownames(cpm_pilot), names(roll_medians) )
head(reorder_gene)

roll_medians <- roll_medians[ reorder_gene ]

stopifnot( all.equal(names(roll_medians), rownames(cpm_pilot) ) )

#Plot
ggplot(data.frame(cv2 = log10(data_cv^2), 
                  roll_medians = roll_medians,
                  mean = log10(apply(2^cpm_pilot, 1, mean)))) +
            geom_point( aes(x = mean, y = cv2), col = "red" ) + 
            geom_point(aes(x = mean, y = roll_medians), col = "blue", alpha = .7) +
            labs(x = "log10 data-wide per gene molecule count",
                 y = "log10 squared coefficient of variation")
```

### compute adjusted CV2

```{r adjust CV2}
# adjusted coefficient of variation on log10 scale
log10cv2_adj <- 
  lapply(1:length(molecules_cv_sample), function(per_label) {
    foo <- log10(molecules_cv_sample[[per_label]]$cv^2) - roll_medians
    return(foo)
})
df_plot$log10cv2_adj <- do.call(c, log10cv2_adj)

#plots
ggplot( df_plot, aes(x = log10(mean), y = log10cv2_adj) ) +
  geom_point( aes(col = as.factor(sample)), cex = .9 ) + 
  facet_wrap( ~ sample) +
  labs(x = "log10(Mean CPM)", y = "log10(Adjusted Squared coefficient of variation") 


ggplot(df_plot, aes(x= factor(sample), y = log10cv2_adj, fill = factor(sample) ) ) +
  geom_violin(alpha = .5) + 
  geom_boxplot(alpha = .01, width = .2, position = position_dodge(width = .9)) +
  labs(xlab = "log10 adjusted Squared coefficient of variation") +
  ggtitle( "log10 CV^2 after adjustment" )
```


