---
title: "DE_analysis"
author: "Anthony Hung"
date: "2019-12-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r loading libraries and data}
library("limma")
library("plyr")
library("edgeR")
library("dplyr")
library("tidyr")
library("ashr")
library("ggplot2")
library("cowplot")
library("VennDiagram")
library("RUVSeq")

#load in filtered count data, RUVs output
filt_counts <- readRDS("data/filtered_counts.rds")
RUVsCPM <- readRDS("data/RUVsCPM.rds")
```

# Limma doesn't deal with technical replicates, so here I randomly sample 1 replicate for each of the 6 individualxcondition

```{r random sample}
#randomly sample 1 replicate from each set of 3 replicates
individuals <- c("18855", "18856", "19160")
treatments <- c("S", "U")

selected_samples <- c()
for(i in individuals){
     for(t in treatments){
          sample_num <- base::sample(c(1:3), 1)
          selected_samples <- c(selected_samples, paste0(i, sep = "_", sample_num, sep = "_", t))
     }
}
selected_samples
randomly_sampled_indices <- match(selected_samples, names(filt_counts))

single_filt_counts <- filt_counts[,randomly_sampled_indices]
anno <- pData(RUVsCPM)[randomly_sampled_indices,]
```

# Model with limma

```{r design-matrix}
#sample details
#anno <- pData(RUVsCPM)

anno$LibraryPrepBatch <- factor(anno$LibraryPrepBatch, levels = c("1", "2"))
anno$Replicate <- factor(anno$Replicate, levels = c("1", "2", "3"))

design <- model.matrix(~treatment + W_1,
                       data = anno)
colnames(design)[1] <- "Intercept"
colnames(design) <- gsub("treatment", "", colnames(design))
colnames(design)
```

```{r fit-model, fig.width=8}
#TMM Normalization
y <- DGEList(single_filt_counts)
y <- calcNormFactors(y)
#Voom for differential expression
v <- voom(y, design)


# Model individual as a random effect (use duplicate correlation function); treatment as a fixed effect, covariates = RUV factors

corfit <- duplicateCorrelation(v, design, block = anno$Individual)
corfit$consensus
v <- voom(y, design, block = anno$Individual, correlation = corfit$consensus)
fit <- lmFit(v, design, block = anno$Individual, correlation = corfit$consensus)
fit <- eBayes(fit)
```


## Assess model results

```{r model-results}
top_treatment <- topTable(fit, coef = "Unstrain")
top_treatment
results_treatment <- topTable(fit, coef = "Unstrain",
                              number = nrow(filt_counts), sort = "none")
ma_treatment <- ggplot(data.frame(Amean = fit$Amean, logFC = fit$coef[, "Unstrain"]),
                       aes(x = Amean, y = logFC)) +
  geom_point() +
  labs(x = "Average expression level", y = "Log fold change",
       title = "Treatment effect")
ma_treatment
hist_treatment <- ggplot(results_treatment, aes(x = P.Value)) +
  geom_histogram(binwidth = 0.01) +
  labs(x = "p-value", y = "Number of genes", title = "Treatment effect")
hist_treatment
```


## Explore top hits

Boxplot function.

```{r boxplot-function}
plot_gene <- function(v, g) {
  # v - An EList object containing log2 counts per million
  # g - character vector of a single gene
  stopifnot(class(v) == "EList",
            is.character(g), length(g) == 1)
  library("tidyr")
  single_gene <- v$E[g, ]
  single_gene_long <- as.data.frame(single_gene)
  colnames(single_gene_long) <- "log2cpm"
  single_gene_long$sample <- rownames(single_gene_long)
  single_gene_long <- separate(single_gene_long, col = "sample", sep = "_",
                                into = c("Individual", "Replicate", "Treatment"))
  single_gene_long$Treatment <- factor(single_gene_long$Treatment, levels = c("S", "U"))
  single_gene_long$Treatment <- revalue(single_gene_long$Treatment, c("S"="Strain", "U"="No Strain"))

  ggplot(single_gene_long, aes(x = Treatment, y = log2cpm, fill = Treatment)) +
    geom_boxplot() +
    labs(title = g, x = "Treatment", y = expression("Expression level (" * log[2] * " cpm)"))
}
```

Treatment

```{r}
p_treatment_1 <- plot_gene(v, rownames(top_treatment)[1]) +
  ylim(3, 11) + theme(legend.position = "bottom")
p_treatment_2 <- plot_gene(v, rownames(top_treatment)[2]) +
  ylim(3, 11) + theme(legend.position = "bottom")
p_treatment_3 <- plot_gene(v, rownames(top_treatment)[3]) +
  ylim(3, 11) + theme(legend.position = "bottom")
p_treatment_4 <- plot_gene(v, rownames(top_treatment)[4]) +
  ylim(3, 11) + theme(legend.position = "bottom")
ggsave("fig-limma-treatment-hit-1.eps", plot = p_treatment_1,
       width = 7, height = 7, units = "in")
plot_grid(p_treatment_1, p_treatment_2, p_treatment_3, p_treatment_4)
```

## Use ash for mutliple testing correction

Treatment effect.

```{r ash-treatment}
# ash_treatment <- ash(betahat = fit$coefficients[, "Unstrain"],
#                      sebetahat = fit$stdev.unscaled[, "Unstrain"] * sqrt(fit$s2.post),
#                      df = fit$df.total)
# class(ash_treatment)
# names(ash_treatment)
# sum(ash_treatment$svalue < .05)
# hist(ash_treatment$svalue)
```

# Plots

```{r Plot Functions}
plot_ma <- function(x, qval) {
  # Create MA plot.
  #
  # x - data frame with topTable and ASH output
  #     (columns logFC, AveExpr, and qvalue)
  # qval - qvalue cutoff for calling a gene DE
  #
  stopifnot(is.data.frame(x), c("logFC", "AveExpr", "qvalue") %in% colnames(x),
            is.numeric(qval), qval <= 1, qval >= 0)
  x$highlight <- ifelse(x$qvalue < qval, "darkred", "gray75")
  x$highlight <- factor(x$highlight, levels = c("darkred", "gray75"))
  ggplot(x, aes(x = AveExpr, y = logFC, color = highlight, shape = highlight)) +
    geom_point() +
    labs(x = "Average expression level", y = "Log fold change") +
    scale_color_identity(drop = FALSE) +
    scale_shape_manual(values = c(16, 1), drop = FALSE) +
    theme(legend.position = "none")
#   scale_color_gradient(low = "red", high = "white", limits = c(0, 0.25))
}

plot_volcano <- function(x, qval) {
  # Create volcano plot.
  #
  # x - data frame with topTable and ASH output
  #     (columns logFC, P.Value, and qvalue)
  # qval - qvalue cutoff for calling a gene DE
  #
  stopifnot(is.data.frame(x), c("logFC", "P.Value", "qvalue") %in% colnames(x),
            is.numeric(qval), qval <= 1, qval >= 0)
  x$highlight <- ifelse(x$qvalue < qval, "darkred", "gray75")
  x$highlight <- factor(x$highlight, levels = c("darkred", "gray75"))
  ggplot(x, aes(x = logFC, y = -log10(P.Value), color = highlight)) +
    geom_point(shape = 1) +
    labs(x = "Log fold change",
         y = expression(-log[10] * " p-value")) +
    scale_color_identity(drop = FALSE) +
    theme(legend.position = "none")
}

plot_pval_hist <- function(x, qval) {
  # Create histogram of p-values.
  #
  # x - data frame with topTable and ash output (columns P.Value and qvalue)
  # qval - qvalue cutoff for calling a gene DE
  #
  stopifnot(is.data.frame(x), c("P.Value", "qvalue") %in% colnames(x))
  x$highlight <- ifelse(x$qvalue < qval, "darkred", "gray75")
  x$highlight <- factor(x$highlight, levels = c("darkred", "gray75"))
  ggplot(x, aes(x = P.Value, fill = highlight)) +
    geom_histogram(position = "stack", binwidth = 0.01) +
    scale_fill_identity(drop = FALSE) +
    labs(x = "p-value", y = "Number of genes")
}
```

```{r use Functions}
# Get model results ------------------------------------------------------------

get_results <- function(x, number = nrow(x$coefficients), sort.by = "none",
                        ...) {
  # x - object MArrayLM from eBayes output
  # ... - additional arguments passed to topTable
  stopifnot(class(x) == "MArrayLM")
  results <- topTable(x, number = number, sort.by = sort.by, ...)
  return(results)
}

run_ash <- function(x, coef) {
  # Perform multiple testing correction with adaptive shrinkage (ASH)
  #
  # x - object MArrayLM from eBayes output
  # coef - coefficient tested by eBayes
  stopifnot(class(x) == "MArrayLM", coef %in% colnames(x$coefficients))
  result <- ash(betahat = x$coefficients[, coef],
                sebetahat = x$stdev.unscaled[, coef] * sqrt(x$s2.post),
                df = x$df.total)
  return(result)
}

tests <- colnames(fit2$coefficients)
results <- vector(length = length(tests), mode = "list")
names(results) <- tests

for (test in tests) {
  # Extract limma results
  results[[test]] <- get_results(fit2, coef = test)
  # Add mutliple testing correction with ASH
  output_ash <- run_ash(fit2, coef = test)
  results[[test]] <- cbind(results[[test]], lfsr = output_ash$lfsr,
                           lfdr = output_ash$lfdr, qvalue = output_ash$qvalue,
                           svalue = output_ash$svalue)
}
```











<!-- Venn diagram -->

<!-- ```{r venn} -->
<!-- ash_treatment_de <- ash_treatment$svalue < .05 -->
<!-- ash_status_de <- ash_status$svalue < .05 -->
<!-- ash_interaction_de <- ash_interaction$svalue < .05 -->
<!-- grid.newpage() -->
<!-- venn_rv <- draw.triple.venn( -->
<!--   area1 = sum(ash_treatment_de), -->
<!--   area2 = sum(ash_status_de), -->
<!--   area3 = sum(ash_interaction_de), -->
<!--   n12 = sum(ash_treatment_de & ash_status_de), -->
<!--   n23 = sum(ash_status_de & ash_interaction_de), -->
<!--   n13 = sum(ash_treatment_de & ash_interaction_de), -->
<!--   n123 = sum(ash_treatment_de & ash_status_de & ash_interaction_de), -->
<!--   category = c("Treatment", "Status", "Interaction"), -->
<!-- #   fill = c("darkolivegreen3", "cadetblue3", "darkorchid"), -->
<!--   alpha = c(0.5, 0.5, 0.5), col = "black", cex = 2, cat.cex = 1.5, -->
<!--   euler.d = FALSE, scaled = FALSE, ind = TRUE) -->
<!-- grid.draw(venn_rv) -->
<!-- ``` -->

<!-- ## Save results of differential expression analysis -->

<!-- Save results from limma and ash. -->

<!-- ```{r save-limma} -->
<!-- saveRDS(v, "../data/results-limma-voom.rds") -->
<!-- saveRDS(fit, "../data/results-limma-fit.rds") -->
<!-- saveRDS(ash_treatment, "../data/results-ash-treatment.rds") -->
<!-- saveRDS(ash_status, "../data/results-ash-status.rds") -->
<!-- saveRDS(ash_interaction, "../data/results-ash-interaction.rds") -->
<!-- ``` -->

<!-- ## Create figure -->

<!-- ```{r fig-limma} -->
<!-- theme_set(theme_bw(base_size = 8)) -->
<!-- theme_update(panel.grid.minor.x = element_blank(), -->
<!--              panel.grid.minor.y = element_blank(), -->
<!--              panel.grid.major.x = element_blank(), -->
<!--              panel.grid.major.y = element_blank()) -->
<!-- fig_limma <- ggdraw() + -->
<!--   draw_plot(ma_treatment,     0.00, 0.67, 0.33, 0.33) + -->
<!--   draw_plot(ma_status,        0.00, 0.33, 0.33, 0.33) + -->
<!--   draw_plot(ma_interaction,   0.00, 0.00, 0.33, 0.33) + -->
<!--   draw_plot(hist_treatment,   0.33, 0.67, 0.33, 0.33) + -->
<!--   draw_plot(hist_status,      0.33, 0.33, 0.33, 0.33) + -->
<!--   draw_plot(hist_interaction, 0.33, 0.00, 0.33, 0.33) + -->
<!--   draw_plot(p_treatment_1,    0.67, 0.82, 0.15, 0.15) + -->
<!--   draw_plot(p_treatment_2,    0.67, 0.67, 0.15, 0.15) + -->
<!--   draw_plot(p_treatment_3,    0.82, 0.67, 0.15, 0.15) + -->
<!--   draw_plot(p_treatment_4,    0.82, 0.82, 0.15, 0.15) + -->
<!--   draw_plot_label(c("A", "B", "C"), c(0.00, 0.00, 0.00), -->
<!--                                     c(1.00, 0.67, 0.33), size = 15) -->
<!-- fig_limma -->
<!-- # Using cowplot ggsave, which by default does not use Dingbats font -->
<!-- ggsave("fig-limma.eps", plot = fig_limma, width = 8, height = 5, units = "in") -->
<!-- ``` -->
