---
title: "Examples"
author: "Anthony Hung"
date: "2020-05-28"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r load data}
library(ggplot2)

overlap_fungenomic <- readRDS("output/overlap_fungenomic.rds")
overlap_crossomic <- readRDS("output/overlap_crossomic.rds")
DE_results <- readRDS("data/DE_results.rds")
least_var_ctl_most_var_treat <- readRDS("output/least_var_ctl_most_var_treat.rds")

#load in V2
v2 <- readRDS("output/voom_results.rds")

# interaction_genes <- readRDS("output/interaction_genes.rds")
# overlap_fungenomic_interaction <- intersect(interaction_genes, overlap_fungenomic)
# overlap_crossomic_interaction <- intersect(interaction_genes, overlap_crossomic)

```

```{r plotting function}
plot_gene <- function(v, g) {
  # v - An EList object containing log2 counts per million
  # g - character vector of a single gene
  stopifnot(class(v) == "EList",
            is.character(g), length(g) == 1)
  library("tidyr")
  single_gene <- v$E[g, ]
  single_gene_long <- as.data.frame(single_gene)
  colnames(single_gene_long) <- "log2cpm"
  single_gene_long$sample <- rownames(single_gene_long)
  single_gene_long <- separate(single_gene_long, col = "sample", sep = "_",
                                into = c("Individual", "Replicate", "Treatment"))

  single_gene_long$Treatment <- gsub('S', 'Strain', single_gene_long$Treatment)
  single_gene_long$Treatment <- gsub('U', 'Control', single_gene_long$Treatment)
  single_gene_long$Treatment <- factor(single_gene_long$Treatment, levels(factor(single_gene_long$Treatment))[c(1,2)])
  
  return(ggplot(single_gene_long, aes(x = Individual, y = log2cpm, fill = Individual)) +
              labs(title = g, y = expression("Expression level (" * log[2] * " cpm)")) + 
              geom_dotplot(binaxis = "y", stackdir = "center", key_glyph = 'rect', dotsize = 0.75) + 
              facet_wrap(~Treatment, strip.position = 'bottom') + 
              stat_summary(fun.data = "mean_sdl", fun.args = list(mult=1)) +
              theme(axis.title.x=element_blank())
              )
}


```

#all top genes

```{r}
for (gene in 1:length(overlap_fungenomic)) {
     print(plot_gene(v2, as.character(overlap_fungenomic[gene])))
}
```

#all interaction genes

```{r}
# for (gene in 1:length(interaction_genes)) {
#      print(plot_gene(v2, as.character(interaction_genes[gene])))
# }
```

#overlap interaction genes w/fungenomic

```{r}
# for (gene in 1:length(overlap_fungenomic_interaction)) {
#      print(plot_gene(v2, as.character(overlap_fungenomic_interaction[gene])))
# }
```


#overlap interaction genes w/cross omic

```{r}
# for (gene in 1:length(overlap_crossomic_interaction)) {
#      print(plot_gene(v2, as.character(overlap_crossomic_interaction[gene])))
# }
```

#candidates (based on variation between ctls and treated samples)

```{r}
for (gene in 1:length(least_var_ctl_most_var_treat)) {
     print(plot_gene(v2, as.character(least_var_ctl_most_var_treat[gene])))
}
```


