---
title: "Pseudobulk"
author: "Anthony Hung"
date: "2020-02-24"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Comparison of single-cell data (pseudobulked) with bulk data from pilot study

```{r load}
library("Seurat")
library("slam")
library("dplyr")
library("RColorBrewer")
library("scales")
library("cowplot")
library("ggplot2")
library("ggfortify")
library("gplots")
library("ggpubr")
library("gridExtra")

# load gene annotations
gene_anno <- read.delim("data/gene-annotation.txt",
                        sep = "\t")
# Load colors 
colors <- colorRampPalette(c(brewer.pal(9, "Blues")[1],brewer.pal(9, "Blues")[9]))(100)
pal <- c(brewer.pal(9, "Set1"), brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))


#load pilot data bulk
raw_counts <- as.matrix(readRDS("data/raw_counts_relabeled.rds"))
# remove rows with 0 counts
raw_counts <- raw_counts[apply(raw_counts, 1, function(x) !all(x==0)),]
dim(raw_counts)

#load pilot data sc
ANT1.2 <- readRDS("data/ANT1_2.rds")
```

# pseudobulk the sc data

```{r pseudobulking}
scData <- data.frame(ANT1.2@assays$RNA@counts)
labels <- ANT1.2@meta.data$labels

PB_NA18856U <- row_sums(scData[, labels == "NA18856_Unstrain"])
PB_NA18855U <- row_sums(scData[, labels == "NA18855_Unstrain"])
PB_NA18855S <- row_sums(scData[, labels == "NA18855_Strain"])
PB_NA19160U <- row_sums(scData[, labels == "NA19160_Unstrain"])
PB_NA19160S <- row_sums(scData[, labels == "NA19160_Strain"])

PB_combined <- cbind(PB_NA18856U, PB_NA18855U, PB_NA18855S, PB_NA19160U, PB_NA19160S)
rownames(PB_combined) <- gene_anno$ensembl_gene_id[match(unlist(rownames(PB_combined)), gene_anno$external_gene_name)]

#Merge
Merged_bulk <- merge(raw_counts, PB_combined, by = "row.names")
row.names(Merged_bulk) <- Merged_bulk$Row.names
Merged_bulk <- Merged_bulk[,-1]
```

# Raw analysis

## Clustering (PCA)

```{r PCA}
# Perform PCA
pca_genes <- prcomp(t(Merged_bulk), scale = T)

#Make PCA plots 

autoplot(pca_genes, label = T)
```

## Clustering (corr heatmap) Spearman

```{r corr heatmap}
#Corr heatmap Spearman
cors <- cor(Merged_bulk, method="spearman", use="pairwise.complete.obs")
heatmap.2(cors, scale="none", margins = c(12, 12), trace='none', denscol="white",
          cexCol = 0.1 + 1/log10(15), cexRow = 0.1 + 1/log10(15))

cors_pseudobulk <- cors[18:22,1:17]
cors_pseudobulk
heatmap.2(cors_pseudobulk, scale="none", margins = c(12, 12), trace='none', denscol="white",
          cexCol = 0.1 + 1/log10(15), cexRow = 0.1 + 1/log10(15))
```



## Correlation between Pseudobulk and bulk from same replicate (raw counts)

```{r corr replicate }
data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18856U`, y = `X18856_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +     
     scale_x_log10()+
     scale_y_log10()

data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18855U`, y = `X18855_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +
     scale_x_log10()+
     scale_y_log10()

data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18855S`, y = `X18855_3_S`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +
     scale_x_log10()+
     scale_y_log10()

data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA19160U`, y = `X19160_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +
     scale_x_log10()+
     scale_y_log10()

data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA19160S`, y = `X19160_3_S`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +
     scale_x_log10()+
     scale_y_log10()
```


## Correlation between Pseudobulk and bulk from different individuals in the same replicate, same treatment (raw counts)

```{r corr individuals}
PB_NA18856U_X18855_3_U <- data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18856U`, y = `X18855_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +     
     scale_x_log10()+
     scale_y_log10()

PB_NA18856U_X19160_3_U <- data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18856U`, y = `X19160_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +     
     scale_x_log10()+
     scale_y_log10()

grid.arrange(PB_NA18856U_X18855_3_U, PB_NA18856U_X19160_3_U)


PB_NA18855U_X18856_3_U <- data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18855U`, y = `X18856_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +     
     scale_x_log10()+
     scale_y_log10()

PB_NA18855U_X19160_3_U <- data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18855U`, y = `X19160_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +     
     scale_x_log10()+
     scale_y_log10()

grid.arrange(PB_NA18855U_X18856_3_U, PB_NA18855U_X19160_3_U)




PB_NA19160U_X18856_3_U <- data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA19160U`, y = `X18856_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +     
     scale_x_log10()+
     scale_y_log10()

PB_NA19160U_X18855_3_U <- data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA19160U`, y = `X18855_3_U`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +     
     scale_x_log10()+
     scale_y_log10()

grid.arrange(PB_NA18855U_X18856_3_U, PB_NA18855U_X19160_3_U)





data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA18855S`, y = `X19160_3_S`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +
     scale_x_log10()+
     scale_y_log10()

data.frame(Merged_bulk)  %>% ggplot(aes(x = `PB_NA19160S`, y = `X18855_3_S`)) +
     geom_point() + 
     geom_smooth(method='lm') + 
     stat_cor(method = "spearman", cor.coef.name = c("rho")) +
     stat_cor(method = "pearson", cor.coef.name = c("r"), label.x.npc = "middle", label.y.npc = "top") +
     scale_x_log10()+
     scale_y_log10()
```

