---
title: "Analysis of Raw Data"
author: "Anthony Hung"
date: "2019-12-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r config}
#configuration
proj_dir <- "/project2/gilad/anthonyhung/Projects/OAStrain_project/"

#order of samples to relabel count matrix (sample ID in format 18855_1_S)
samplenames <- c("18855_1_S","18855_1_S","18855_1_S","18855_1_S")
```


# Load in bulk RNA sequencing data from pilot experiment and visualize correlations between samples 

```{r load libraries and data}
library("gplots")
library("ggplot2")
library("edgeR")
library("RColorBrewer")
library("scales")

# Load colors 
colors <- colorRampPalette(c(brewer.pal(9, "Blues")[1],brewer.pal(9, "Blues")[9]))(100)
pal <- c(brewer.pal(9, "Set1"), brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))

# load in counts
raw_counts <- read.table(paste0(proj_dir, "out/counts/counts.txt"), header = T)

# assign row.names
row.names(raw_counts) <- raw_counts$Geneid

# assign col.names
col.names(raw_counts) <- samplenames

# exclude extra data columns
raw_counts <- raw_counts[, -c(1:6)] 
head

# save modified raw count data matrix
saveRDS(raw_counts, "data/raw_counts_relabeled.rds")

# Check that there's no "NAs" in the data
summary(apply(raw_counts, 1, var) == 0) 

#Sample information
samples <- read.csv("data/Sample.info.RNAseq.csv")
head(samples)
```

# Perform PCA and hierarchical clustering on raw data

```{r PCA and corr heatmap}
#load PCA function
source("code/PCA_fn.R")

# Clustering (original code from Julien Roux)
cors <- cor(raw_counts, method="spearman", use="pairwise.complete.obs")


heatmap.2( cors, scale="none", col = colors, margins = c(12, 12), trace='none', denscol="white", labCol=labels, ColSideColors=pal[as.integer(as.factor(samples$Individual))], RowSideColors=pal[as.integer(as.factor(samples$treatment))+3], cexCol = 0.2 + 1/log10(15), cexRow = 0.2 + 1/log10(15))
```


#Perform PCA and color by factors to look for any potential correlations

```{r}
# Perform PCA
pca_genes <- prcomp(t(raw_counts), scale = F)
scores <- pca_genes$x


#Make PCA plots with the factors colored by individual

### PCs 1 and 2 Raw Data
for (n in 1:1){
  col.v <- pal[as.integer(samples$Individual)]
  plot_scores(pca_genes, scores, n, n+1, col.v)
}

### PCs 3 and 4 Raw Data

for (n in 3:3){
  col.v <- pal[as.integer(samples$Individual)]
  plot_scores(pca_genes, scores, n, n+1, col.v)
}

#Make PCA plots with the factors colored by treatment

### PCs 1 and 2 Raw Data
for (n in 1:1){
  col.v <- pal[as.integer(samples$treatment)]
  plot_scores(pca_genes, scores, n, n+1, col.v)
}

### PCs 3 and 4 Raw Data

for (n in 3:3){
  col.v <- pal[as.integer(samples$treatment)]
  plot_scores(pca_genes, scores, n, n+1, col.v)
}
```