---
title: "Analysis of Technical factors"
author: "Anthony Hung"
date: "2019-12-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Examine normalized/filtered data and see if any PCs correlate with technical factors

```{r load data libraries}
library("polycor")

#load in normalized/filtered data
```

# PCA and hierarchical clustering of normalized and filtered data

```{r clustering}
#Load PCA Function
source("code/PCA_fn.R")


# Clustering (original code from Julien Roux)
cors <- cor(raw_counts, method="spearman", use="pairwise.complete.obs")


heatmap.2( cors, scale="none", col = colors, margins = c(12, 12), trace='none', denscol="white", labCol=labels, ColSideColors=pal[as.integer(as.factor(samples$Species))], RowSideColors=pal[as.integer(as.factor(samples$Tissue))+9], cexCol = 0.2 + 1/log10(15), cexRow = 0.2 + 1/log10(15))
```

#Perform PCA and color by factors to look for any potential correlations

```{r PCA}
# Perform PCA
pca_genes <- prcomp(t(raw_counts), scale = F)
scores <- pca_genes$x


#Make PCA plots with the factors colored by tissue

### PCs 1 and 2 Raw Data
for (n in 1:1){
  col.v <- pal[as.integer(samples$Tissue)]
  plot_scores(pca_genes, scores, n, n+1, col.v)
}

### PCs 3 and 4 Raw Data

for (n in 3:3){
  col.v <- pal[as.integer(samples$Tissue)]
  plot_scores(pca_genes, scores, n, n+1, col.v)
}
```


# Check that technical factors do not correlate with PCs using polycor


